<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco [
    <!ELEMENT banco (cuenta+)>
    <!ELEMENT cuenta (sucursal,saldo,cliente)>
    <!ELEMENT sucursal (#PCDATA)>
    <!ELEMENT saldo (#PCDATA)>
    <!ELEMENT cliente (nombre,calle,ciudad)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>

    <!ATTLIST cliente 
        ID CDATA #IMPLIED>

    <!ATTLIST cuenta 
        num_cuenta CDATA #IMPLIED
        titular CDATA #IMPLIED>
]>
<banco>
    <cuenta num_cuenta="12345" titular="Juan Perez">
        <sucursal>Sucursal A</sucursal>
        <saldo>5000</saldo>
        <cliente ID="001">
            <nombre>Juan Perez</nombre>
            <calle>Calle Principal, 123</calle>
            <ciudad>Ciudad Ejemplo</ciudad>
        </cliente>
    </cuenta>
    <cuenta num_cuenta="67890" titular="Maria Lopez">
        <sucursal>Sucursal B</sucursal>
        <saldo>7500</saldo>
        <cliente ID="002">
            <nombre>Maria Lopez</nombre>
            <calle>Avenida Secundaria, 456</calle>
            <ciudad>Otra Ciudad</ciudad>
        </cliente>
    </cuenta>
</banco>
